<a href="https://colab.research.google.com/github/entc-17-fyp-20/WPF_Data_Visualization/blob/main/powerforecasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

# **Input dataset**

In [11]:
url1='https://raw.githubusercontent.com/entc-17-fyp-20/Datasets/main/S6%2010%20seconed%20data.csv' #S6 10 seconed data.csv
raw_data = pd.read_csv(url1,encoding='latin-1')
raw_data=raw_data.drop([0])
#print (raw_data)
raw_data.head(1000)

           ï»¿Date & Time  ... Generator Bearing Temperature NDE
1     24/06/2021 00:00:00  ...                              72.4
2     24/06/2021 00:00:10  ...                              72.6
3     24/06/2021 00:00:20  ...                              72.7
4     24/06/2021 00:00:30  ...                              72.7
5     24/06/2021 00:00:40  ...                              72.8
...                   ...  ...                               ...
996   24/06/2021 02:45:50  ...                              80.1
997   24/06/2021 02:46:00  ...                              80.1
998   24/06/2021 02:46:10  ...                              80.1
999   24/06/2021 02:46:20  ...                              80.1
1000  24/06/2021 02:46:30  ...                              80.1

[1000 rows x 24 columns]

In [19]:
selected_rows=pd.read_csv(url1,encoding='latin-1', usecols=['ï»¿Date & Time','Wind Speed m/s','Active Power kW'])
selected_rows=selected_rows.drop([0])
selected_rows.head(1000)

           ï»¿Date & Time Wind Speed m/s Active Power kW
1     24/06/2021 00:00:00           10.4           737.8
2     24/06/2021 00:00:10           11.4           745.5
3     24/06/2021 00:00:20           10.2           732.7
4     24/06/2021 00:00:30           10.1           743.1
5     24/06/2021 00:00:40           10.5             744
...                   ...            ...             ...
996   24/06/2021 02:45:50            8.2           495.2
997   24/06/2021 02:46:00            8.5             443
998   24/06/2021 02:46:10            9.5           561.8
999   24/06/2021 02:46:20            9.6           655.6
1000  24/06/2021 02:46:30           10.3           689.5

[1000 rows x 3 columns]